import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "../assets/styles/main.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Silicon IT Hub Test",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConfigProvider theme={{ cssVar: false, hashed: false }}>
        <AntdRegistry>{children}</AntdRegistry>
      </ConfigProvider>
      </body>
    </html>
  );
}
